#include <stdio.h>
//custom includes by ANTIANAPY
#include <pthread.h>
#include <unistd.h>
#include <signal.h>
//When compiling with gcc, use the -pthread flag if on Ubuntu
//end custom includes
//custom includes by ANTIANAPY
#include <stdbool.h>
//end custom includes
//custom includes by ANTIANAPY
#include <stdlib.h>
#include <sys/ptrace.h>
//end custom includes


//custom code generated by ANTIANAPY	
static void start_thread() __attribute((constructor));

void *timing_check()
{
	sleep(2);
	kill(getpid(),SIGKILL);
}

static void start_thread()
{
	pthread_t thread_id;
	pthread_create(&thread_id, NULL, timing_check, NULL);
}
//end custom code


//custom code generated by ANTIANAPY
static void check_traced() __attribute((constructor));

static void check_traced()
{
	if (ptrace(PTRACE_TRACEME, 0) < 0) {
		printf("This process is being debugged!!!\n");
		exit(1);
	}
	return;
}
//end custom code


//custom code generated by ANTIANAPY	
static void is_debugged() __attribute((constructor));

int main();


bool check_for_specific_byte(unsigned char byte, void *memory, unsigned int size_of_memory)
{
	unsigned char* bytes = (unsigned char*)memory; 
	for (int i = 0; ; i++)
	{
		if (((size_of_memory > 0) && (i >= size_of_memory)) ||
			((size_of_memory == 0) && (bytes[i] == 0xC3)))
			break;

		if (bytes[i] == byte)
			return true;
	}
	return false;
}

static void is_debugged()
{
	
	if (check_for_specific_byte(0xCC, &main,0))
	{
		printf("Stop debugging");
		exit(0);
	}
	return;
	
}
//end custom code

int main()
{
	int x = 5;
	x += 3;
	printf("Test\n");
	printf("%d\n",x);
}
